services:
  api:
    image: lodgify/movies-api:3
    ports:
      - "7172:80"
      - "7443:443"
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - FailurePercentage=90
  cache:
    image: "redis"
    restart: unless-stopped
    ports:
      - "6379:6379"

  apiapplication:
    image: ${DOCKER_REGISTRY-}apiapplication
    build:
      context: .
      dockerfile: ApiApplication/Dockerfile
    ports:
      - "7173:80"
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Redis__ConnectionString=cache:6379
      - MoviesService__BaseUrl=https://api:443
